### ISSUE TITLE
How Transpile: json schema to es5

### ISSUE THREAD

**Issue by miladezzat** [willfarrell/ajv-cmd#1]
## Description
- when i am transpile the JSON schema it's convert to es6, i want to add options to create `es5`

**Comment by willfarrell** [comment]
I imagined the output of ajv-cmd would be a pre-step in a build process to convert all schema jsons to validator js, then those would be imported to one own js that are then transpiled to whatever you need into the final bundle.

Can you share your uses case?

**Comment by miladezzat** [comment]
Well, i use commonJs on my project, when I run the pre transpiling JSON schema, it's transpile to es6 and i want to transpile it to es5
<img width="880" alt="Screenshot 2022-12-08 at 7 45 14 PM" src="https://user-images.githubusercontent.com/27713902/206525481-2a150882-1ae3-41bd-903b-b2c086d68773.png">

**Comment by willfarrell** [comment]
After some reflection, I decided I don't want to support commonjs in this project. The official [ajv-cli](https://github.com/ajv-validator/ajv-cli) already does this well and the ecosystem moving towards esm only. Sorry, only have so much free time. Hope `ajv-cli` meets your needs.

I made this project to add in the features I needed that were not being merged in like [esm](https://github.com/ajv-validator/ajv-cli/pull/200), [uri-resolver](https://github.com/ajv-validator/ajv-cli/pull/210), with modern defaults and smaller bundles.

**Comment by willfarrell** [comment]
I imagine you're looking into this for Middy. If you do choose to add in `ajv-cli` for cjs output, a PR to add it to the docs would be welcome.
