### ISSUE TITLE
Esbuild listed as a dependency creates 200mb+ size

### ISSUE THREAD

**Issue by wehnerjp** [willfarrell/ajv-cmd#4]
Currently, trying to use middy/validator in a lambda layer.  The ajv-cmd package lists esbuild as a dependency.  Although it is not needed at runtime in the layer, it is still included.  This creates a problem with the size being far larger than a layer can handle.  The layer is written in js and shouldn't need to use a bundler.

**Comment by willfarrell** [comment]
v5 of Middy has been updated to not require this package.

**Comment by wehnerjp** [comment]
For those of you who find this thread before v5 comes out this is the workaround my colleague and I used to omit the esbuild package without having to implement a tree shaking system in our lambda layers:


package.json
```
    "overrides": {
    "esbuild": "npm:dry-uninstall"
  },
```
